### PR TITLE
Enforce non-null for createdAt/updatedAt

### PR DESCRIPTION
**Pull request by Betree**

### CODE REVIEW

**Review by znarf — CHANGES_REQUESTED** [review]
Doesn't seem to take care of updatedAt

**Comment by Betree** [comment]
> Doesn't seem to take care of updatedAt

I was initially seeding it as well but rolled back that part as many collectives have an empty `updatedAt`. I thought it could be interesting to keep allowing an empty `updatedAt` for things that have never been updated.

I've updated the PR description, but can rollback the code if you think we should not support this.

**Comment by znarf** [comment]
The expected behavior is to always updatedAt set and default to createdAt as initial value.

**Comment by Betree** [comment]
> The expected behavior is to always `updatedAt` set and default to `createdAt` as initial value.

I'll bring back the changes then. Also gonna look at other models to fix everything at once.

**Comment by Betree** [comment]
Tables to enforce non-null constraints for:
- Activities (createdAt)
- Applications
- Collectives
- Comments
- ConnectedAccounts
- CurrencyExchangeRates (updatedAt)
- LegalDocuments
- Members
- Notifications
- OAuthAuthorizationCodes
- Orders
- PaymentMethods
- PersonalTokens
- RequiredLegalDocuments
- Subscriptions
- SuspendedAssets (updatedAt)
- Tiers
- Transactions (createdAt)
- Updates
- Users
- UserTokens

**Comment by Betree** [comment]
Test running the migration locally on a fresh prod dump. Activities are slow (as expected); the rest is under control. I've voluntarily ignored `Transactions` since dropping & recreating the materialized view would have been very expensive. We can consider migrating next time we revamp them - since there were no null values, it doesn't sound urgent.

I still have to look into a few E2E tests that are failing, likely because they relied on an item being ordered differently due to an empty `createdAt`/`updatedAt`.

> == 20240130172551-non-null-created-at-updated-at: migrating =======
> Seed Users: 123.14ms
> Seed Collectives: 658.442ms
> **Seed Activities: 19.845s**
> **Add constraints for Activities: 17.576s**
> Add constraints for Applications: 3.431ms
> Add constraints for Collectives: 1.207s
> Add constraints for Comments: 99.603ms
> Seed timestamps for ConnectedAccounts: 80.031ms
> Add constraints for ConnectedAccounts: 28.878ms
> Add constraints for CurrencyExchangeRates: 2.131s
> Add constraints for LegalDocuments: 7.457ms
> Seed timestamps for Members: 205.916ms
> Add constraints for Members: 111.477ms
> Seed timestamps for Notifications: 9.593ms
> Add constraints for Notifications: 5.046ms
> Add constraints for OAuthAuthorizationCodes: 6.615ms
> Add constraints for Orders: 664.535ms
> Seed timestamps for PaymentMethods: 446.061ms
> Add constraints for PaymentMethods: 167.203ms
> Add constraints for PersonalTokens: 3.723ms
> Add constraints for RequiredLegalDocuments: 1.995ms
> Seed timestamps for Subscriptions: 37.899ms
> Add constraints for Subscriptions: 21.353ms
> Add constraints for SuspendedAssets: 1.347ms
> Seed timestamps for Tiers: 57.154ms
> Add constraints for Tiers: 24.129ms
> Add constraints for Updates: 28.078ms
> Add constraints for Users: 594.928ms
> Add constraints for UserTokens: 7.153ms
> == 20240130172551-non-null-created-at-updated-at: migrated (44.709s)

**Comment by Betree** [comment]
@znarf New version ready for review.

**Comment by Betree** [comment]
Migration log on production, for reference:

> remote:        == 20240130172551-non-null-created-at-updated-at: migrating =======
> remote:        Seed Users: 3.306s
> remote:        Seed Collectives: 597.059ms
> remote:        Seed Activities: 2:02.718 (m:ss.mmm)
> remote:        Add constraints for Activities: 1:51.942 (m:ss.mmm)
> remote:        Add constraints for Applications: 206.919ms
> remote:        Add constraints for Collectives: 15.625s
> remote:        Add constraints for Comments: 1.365s
> remote:        Seed timestamps for ConnectedAccounts: 569.268ms
> remote:        Add constraints for ConnectedAccounts: 59.304ms
> remote:        Add constraints for CurrencyExchangeRates: 7.747s
> remote:        Add constraints for LegalDocuments: 74.281ms
> remote:        Seed timestamps for Members: 1.757s
> remote:        Add constraints for Members: 3.238s
> remote:        Seed timestamps for Notifications: 97.092ms
> remote:        Add constraints for Notifications: 13.013ms
> remote:        Add constraints for OAuthAuthorizationCodes: 53.67ms
> remote:        Add constraints for Orders: 12.477s
> remote:        Seed timestamps for PaymentMethods: 7.583s
> remote:        Add constraints for PaymentMethods: 451.534ms
> remote:        Add constraints for PersonalTokens: 57.833ms
> remote:        Add constraints for RequiredLegalDocuments: 15.176ms
> remote:        Seed timestamps for Subscriptions: 753.076ms
> remote:        Add constraints for Subscriptions: 66.498ms
> remote:        Add constraints for SuspendedAssets: 23.004ms
> remote:        Seed timestamps for Tiers: 522.684ms
> remote:        Add constraints for Tiers: 1.886s
> remote:        Add constraints for Updates: 695.443ms
> remote:        Add constraints for Users: 8.152s
> remote:        Add constraints for UserTokens: 180.37ms
> remote:        == 20240130172551-non-null-created-at-updated-at: migrated (302.392s)

**Comment by znarf** [comment]
Awesome

**Pull request merged**
