### PR TITLE
Replaced rounded monetary amounts in emails with non-rounded ones

### PR DESCRIPTION
**Pull request by Gbahdeyboh**

### CODE REVIEW

**Comment by Betree** [comment]
This is the fix for https://github.com/opencollective/opencollective/issues/1773

@Gbahdeyboh It would be great to make changes on the same pull request next time, it is helpful for us to be able to see the full history on the same PR :wink: 

Can you take some screenshots of the emails to add in the description? Maildev can help you to do that: https://github.com/opencollective/opencollective-api/blob/master/docs/emails.md

**Comment by jeffin143** [comment]
@Gbahdeyboh , are you still working on it :)

**Comment by Gbahdeyboh** [comment]
@jeffin143 , i had some trouble visualizing it. For some reason, postgresql isn't working as expected on my laptop

**Comment by Betree** [comment]
@Gbahdeyboh we can't merge un-tested code. We have to make sure that this works and that it doesn't break anything.

We have some documentation that may help you to setup postgres, let me know if it helps:
https://github.com/opencollective/opencollective-api/blob/master/docs/postgres.md

**Comment by jeffin143** [comment]
@Gbahdeyboh , Since it was difficult for you to setup the database, I pulled your branch and ran a test

@Betree - Here are the test for this branch 

For approve Expense

Screenshot from 2019-10-25 21-14-24


And for Create Expense
Screenshot from 2019-10-25 21-07-51

I couldn't test it for Paid expense since I couldn't be a fiscal host :)

**Comment by Gbahdeyboh** [comment]
Thanks @jeffin143, I guess everything works as expected now?

**Comment by Betree** [comment]
Thanks for testing and providing screenshots @jeffin143 :tada:

**Pull request merged**
