### PR TITLE
Deprecate apollo-errors

### PR DESCRIPTION
**Pull request by kewitz**
Typing should prevent us from making the same mistake again and it will also suggest what properties else you could be using.

### CODE REVIEW

**Comment by znarf** [comment]
> the same mistake again

@kewitz What are you talking about?

**Comment by Betree** [comment]
@znarf I think Leo is referring to the misuse of the errors where we pass the message directly rather than in an object (ie. `new Unauthorized({ message: '' })`).

I agree with the change, I've misused this constructor a bunch of time. It's strange that we have to pass the `message` for an error through an object rather than a direct parameter.

**Comment by znarf** [comment]
Should we change the API and remove the `message` everywhere then?

**Comment by kewitz** [comment]
My suggestion, in that case, would be to deprecate the outdated `apollo-errors` and extend the native ApolloError.

**Comment by znarf** [comment]
@kewitz I'm open to it.

**Comment by kewitz** [comment]
Squashed the first commit, since it was related to the previous refactor.

**Comment by znarf** [comment]
Please rebase and merge!

**Pull request merged**
