### PR TITLE
runs server on new port in test; closes #335

### LINKED ISSUE #335: cannot run tests and server at once
There's a port collision.  either use get-port package or select a diff port for tests?

### PR DESCRIPTION
**Pull request by boneskull**
- env var `API_PORT` is now respected; ~~`PORT` is no longer respected~~ (see OpenCollective/opencollective-website#230)
- `test_e2e.sh` sets `API_PORT` and `API_URL` (used by Selenium) in dev mode
- set `API_PORT` in unit test fixture as well
- renamed `test/set_pg_database.js` to more generic `test/fixture.js` since it's no longer just configuring the db env

**UPDATE**: Heroku needs `PORT`, so we'll use `API_PORT` if present, otherwise `PORT`, otherwise the hardcoded default.

### CODE REVIEW

**Comment by sedubois** [comment]
AFAIK `PORT` is a reserved env var provided by Heroku, we need to use that one

**Comment by boneskull** [comment]
@sedubois how can I assert that?

**Comment by sedubois** [comment]
https://devcenter.heroku.com/articles/dynos#web-dynos

**Comment by boneskull** [comment]
@sedubois I'll modify this PR appropriately (and opencollective/website#232)

**Comment by boneskull** [comment]
@sedubois updated both

**Comment by asood123** [comment]
I'm not sure why this failed. @sedubois

**Comment by sedubois** [comment]
Me neither. @boneskull could you rebase on master just to make sure it's not related to the repo name change?

**Comment by boneskull** [comment]
closing since we can't CI the forks

**Pull request closed without merging**
