### PR TITLE
Use aws-sdk instead of knox

### PR DESCRIPTION
**Pull request by JohnTitor**
CC https://github.com/opencollective/opencollective/issues/1880

### CODE REVIEW

**Comment by JohnTitor** [comment]
Hmm, CI doesn't run because this is sent via my fork?

**Comment by znarf** [comment]
@JohnTitor yes, this is it, I'll check if we can activate CI for forks. In the meantime, I will push the branch here to trigger it.

**Comment by JohnTitor** [comment]
@znarf Thanks!

**Comment by JohnTitor** [comment]
Uh, I should get 200 on image tests. Will take a look later.

**Comment by znarf** [comment]
@JohnTitor cool, try to run the test locally?

**Comment by JohnTitor** [comment]
@znarf I'm testing on my CircleCI, is this okay?

**Comment by znarf** [comment]
@JohnTitor Up to you, it's usually faster to troubleshoot locally first.

**Comment by JohnTitor** [comment]
Uh, the tests are never passed. I'll close this for now to release the issue. Take a look later.

**Pull request closed without merging**
