### PR TITLE
SanitizeHtml: Allow figure with content-type for iframes

### PR DESCRIPTION
**Pull request by Betree**
For https://github.com/opencollective/opencollective-frontend/pull/6042

### CODE REVIEW

**Comment by SudharakaP** [comment]
@Betree : Thanks for adding this. But something not working correctly before adding this `figure` for content types? 🤔

**Comment by Betree** [comment]
@SudharakaP responsiveness. Before that, the height was fixed to 400px so on mobile you ended up with two black stripes above and below the video. Having this content-type allowed us to add [this CSS rule](https://github.com/opencollective/opencollective-frontend/pull/6042/commits/077ef4060b50ef57c3af8fba2de3dcac55970f28#diff-7c66bed1a72345f8e57ccf8d28acc894e870d12efc4045b9ab242b0a386b064cR110) which creates a real 16:9 container.

**Comment by Betree** [comment]
@SudharakaP 

Before:
image

After:
image

**Comment by SudharakaP** [comment]
> @SudharakaP responsiveness. Before that, the height was fixed to 400px so on mobile you ended up with two black stripes above and below the video. Having this content-type allowed us to add [this CSS rule](https://github.com/opencollective/opencollective-frontend/pull/6042/commits/077ef4060b50ef57c3af8fba2de3dcac55970f28#diff-7c66bed1a72345f8e57ccf8d28acc894e870d12efc4045b9ab242b0a386b064cR110) which creates a real 16:9 container.

@Betree : Thanks. Looks wonderful now. 😄

**Pull request merged**
