### PR TITLE
Add Support to Convert User Account to Org

### PR DESCRIPTION
**Pull request by SudharakaP**
Related to https://github.com/opencollective/opencollective/issues/5771

Related Front-end PR: https://github.com/opencollective/opencollective-frontend/pull/8647

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
I'll let @znarf provide a more comprehensive review as he's more experienced with the process. Some concerns I have:
- This needs unit tests
- What if someone tries to convert a guest account?
- I'm wondering about the `isActive` column value, need to check the DB data
- Note that location is private for users but public for organizations; this should be clearly stated by support in appropriate cases

**Comment by znarf** [comment]
> This needs unit tests

Todo

> What if someone tries to convert a guest account?

This should be prevented until we have such case and sure we want to support it.

**Comment by SudharakaP** [comment]
@Betree : 

> I'll let @znarf provide a more comprehensive review as he's more experienced with the process. Some concerns I have:
> 
>     * This needs unit tests

Added. 👍🏽 

>     * What if someone tries to convert a guest account?

For now I've prevented that. 👍🏽 
 
>     * I'm wondering about the `isActive` column value, need to check the DB data

It seems that when we are creating a new user we set `isActive=false`.

https://github.com/opencollective/opencollective-api/blob/1698e37291ae2f0e21b1ab4a58958059c414bf12/server/models/User.ts#L414

In production we only have 3 users who has `isActive=true`. Not sure exactly how these users have this value set to true, but wondering how this is relevant to this situation? 🤔  
 
>     * Note that location is private for users but public for organizations; this should be clearly stated by support in appropriate cases

I've added a note in the front-end so that the person who's doing this is reminded of this and could notify the user.

image

**Review by znarf — APPROVED** [review]
Works for me. Maybe Ben for a final look but not mandatory.

**Comment by SudharakaP** [comment]
> Works for me. Maybe Ben for a final look but not mandatory.

@Betree : You wanna look at this one more, or are we good to merge? 😸

**Review by Betree — COMMENTED** [review]
No blocker for me

**Pull request merged**
