### PR TITLE
Attach Receipt to Paid Charge Expenses

### PR DESCRIPTION
**Pull request by kewitz**
Resolves https://github.com/opencollective/opencollective/issues/4067

### CODE REVIEW

**Review by Betree — APPROVED** [review]
Looking good :+1:

**Comment by Betree** [comment]
@kewitz no emergency since the feature is not public yet, but I just realized we will need to update the code for tax forms to make sure charges are not counted in the calculation:
- https://github.com/opencollective/opencollective-api/blob/f9fc75b1e1885767e836a7259cc1c6dfb69503e8/server/lib/queries.js#L895
- https://github.com/opencollective/opencollective-api/blob/f9fc75b1e1885767e836a7259cc1c6dfb69503e8/server/lib/queries.js#L936

**Comment by kewitz** [comment]
@Betree could you take a quick look at the tax query refact? https://github.com/opencollective/opencollective-api/pull/5720/commits/ef727d8245b88d946d75ae5943d4b96f43e650d4?

**Review by Betree — APPROVED** [review]
Looking good!

**Pull request merged**
