### PR TITLE
Fetch updates across child collectives

### PR DESCRIPTION
**Pull request by xdamman**

### CODE REVIEW

**Comment by xdamman** [comment]
@znarf when you have a chance, can you look into why the tests aren't even starting?
This is the error message (never seen it before):

```
Starting container circleci/node:10.3.0
  image cache not found on this host, downloading circleci/node:10.3.0

  Error pulling image circleci/node:10.3.0: Error response from daemon: received unexpected HTTP status: 503 Service Unavailable... retrying
  image cache not found on this host, downloading circleci/node:10.3.0

Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
```

**Comment by znarf** [comment]
@xdamman do you want to merge that now that tests are passing?

**Comment by znarf** [comment]
@xdamman should we merge or forget about that?

**Comment by znarf** [comment]
Lack of activity closing.

**Pull request closed without merging**
