### PR TITLE
Convert Application Model into typescript

### PR DESCRIPTION
**Pull request by TimotheeHrl**
I there I did a first model conversion into typescript :)
Please let me know if there anything to fix.
Have a good day

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
Issue link: https://github.com/opencollective/opencollective/issues/5893

@TimotheeHrl Thanks for starting the work on this one! It looks like it's not replacing the old model, `server/models/Application.js` is still there. Also typescript is not happy with the result, see https://github.com/opencollective/opencollective-api/actions/runs/3225490068/jobs/5311116121. You can run `npm run type:check` to test that locally.

**Comment by Betree** [comment]
@TimotheeHrl Any news on that one? If you don't have the time to work on it anymore that's perfectly fine, just let us know so someone else can take over.

**Comment by TimotheeHrl** [comment]
Hi Betree, I'm sorry I haven't pro-active on this one. I figured it was hard for me the change model one by one, and a bit discouraged since I'm not familliar with sequelize... 
So yes, off course you can assign it to someone else.

**Comment by Betree** [comment]
Thanks for starting it!

**Pull request closed without merging**
