### PR TITLE
Make the `graphql-inspector` version fixed

### PR DESCRIPTION
**Pull request by SudharakaP**
Resolve https://github.com/opencollective/opencollective/issues/5724

### CODE REVIEW

**Review by znarf — APPROVED** [review]
Great, let's do this for now.

**Review by znarf — CHANGES_REQUESTED** [review]
Hold on. It seems master is working fine now.

**Comment by SudharakaP** [comment]
> Hold on. It seems master is working fine now.

Yes that's because after my report they fixed it just some hours back and pushed a new version (v3.2.0). 😉 

https://github.com/kamilkisiela/graphql-inspector/issues/2128#issuecomment-1176314788

I've adjusted this PR to use that new version (v3.2.0).

**Comment by znarf** [comment]
@SudharakaP I'm not sure if we need to fix the version. Will we have the automated dependency updates for it?

@Betree what do you think?

**Comment by Betree** [comment]
> @SudharakaP I'm not sure if we need to fix the version. Will we have the automated dependency updates for it?
> 
> @Betree what do you think?

Dependabot supports updating Github actions. I'm not sure about renovate?

**Comment by znarf** [comment]
Good for me if updates are automatically managed.

**Pull request merged**
