### PR TITLE
squelch Bluebird warnings when running tests; closes #341

### LINKED ISSUE #341: bluebird warnings are noisy

### PR DESCRIPTION
**Pull request by boneskull**
that oughtta do it.

### CODE REVIEW

**Comment by sedubois** [comment]
Can you show which warnings you mean? Bluebird warnings are there for a reason, right? Can we instead fix the root cause?

**Comment by boneskull** [comment]
@sedubois 

yes, let me find examples.

**Comment by sedubois** [comment]
And if we did need to change environment across all mocha tests, I'd find `test/setup.js` a more logical place

**Comment by boneskull** [comment]
I'm going to abandon this for now.

**Pull request closed without merging**
