### PR TITLE
Add Github handle to Collective

### PR DESCRIPTION
**Pull request by Betree**
Resolves opencollective/opencollective#1343

--------------

This PR adds a `githubHandle` field in `Collectives` table that stores organization or user Github handle. It allows for any user or organization to set a Github account handle.

The [organization handle](https://user-images.githubusercontent.com/1556356/46889800-15f1ff80-ce65-11e8-9e36-a3b020edf879.png) length limitation and [user handle](https://user-images.githubusercontent.com/1556356/46889801-18545980-ce65-11e8-855c-61b976e35bdb.png) limitation is 39 characters.

### CODE REVIEW

**Comment by znarf** [comment]
Looks good. I'm not sure where you got the 39 characters limitation. Any additional insight?

**Comment by Betree** [comment]
@znarf You get the above error messages when filling the forms on:
* https://github.com/organizations/new
* https://github.com/join (must be logged out)

**Comment by marcogbarcellos** [comment]
looks good to me too. thanks @Betree ! 👍

**Comment by BenJam** [comment]
Thanks folks!

**Pull request merged**
