### PR TITLE
refactor(applications): check CollectiveId instead of CreatedByUser

### PR DESCRIPTION
**Pull request by bolariin**
resolves https://github.com/opencollective/opencollective/issues/2029

### CODE REVIEW

**Comment by bolariin** [comment]
> We have two applications in the database with `CollectiveId` = NULL (sounds like something that we should not allow in the first place). We should do something about them before merging, otherwise we're going to break them.

Would it possible to update those rows?

> ), tho I think should probably also hide the whole list in the `applications` resolver if you're not allowed to - I don't see any benefit in allowing other users to list your applications (id, type, name, description).

I'm not sure I completely understand when you say hide the whole list in the `applications` resolver

**Comment by Betree** [comment]
> Would it possible to update those rows?

Yes, the best to do that is to create a migration with `npm run db:migration:create -- --name enforce-applications-collective-id`.

You can use the following query to update the applications:

```sql
UPDATE ONLY "Applications" a
SET "CollectiveId" = u."CollectiveId"
FROM "Users" u 
WHERE u.id = a."CreatedByUserId" 
AND a."CollectiveId" IS NULL
```

Then, in the same migration. we should also add a `NOT NULL` constraint to the `Applications.CollectiveId` column to make sure it doesn't happens in the future. Let me know if you need more info on that.

> I'm not sure I completely understand when you say hide the whole list in the applications resolver

In my opinion, there's no reason to allow users to list someone else's applications. So in the application resolver (https://github.com/opencollective/opencollective-api/blob/0f710e52086298cd7b1255a8eb34a8935978b5d2/server/graphql/v1/CollectiveInterface.js#L1798) I'd rather add:

```es6
applications: {
  type: new GraphQLList(ApplicationType),
  resolve(userCollective, _, req) {
    if (req.remoteUser && req.remoteUser.isAdmin(userCollective.id)) {
      return models.Application.findAll({
        where: { CollectiveId: userCollective.id },
      });
    }
  },
},
```

**Comment by znarf** [comment]
@Betree the two applications mentioned are different from the others, we should double check their use case internally.

**Comment by Betree** [comment]
@znarf You mean by contacting the users?

In any case I don't think that it should prevent us from fixing them, adding their `CollectiveId` should not break anything.

**Comment by znarf** [comment]
@Betree I mean: let's discuss these specific cases elsewhere.

**Comment by Betree** [comment]
@znarf Yes no problem with that, but I still think that we should create this migration no? It doesn't cost much and adding a constraint to the DB will make sure that this doesn't happen again in the future. It's also a requirement for this PR to solve it before merging because otherwise we will break these two applications.

**Comment by znarf** [comment]
Thank you @bolariin. Merging!

**Pull request merged**
