### PR TITLE
Pledges: Bypass Github validations on CI

### PR DESCRIPTION
**Pull request by Betree**
https://github.com/opencollective/opencollective-frontend/pull/3803 progress is blocked because Github validations fails for verifying the pledged repo/org. This is because we don't have a Github token setup, so the requests can't be triggered.

Alternatives solutions:
- Setup a dummy Github account and set the token in CI
- Completely bypass the Github verification on CI rather than relying on the name starting with `valid`. Simpler, but we won't be able to test the errors cases.

### CODE REVIEW

**Comment by znarf** [comment]
I'm happy to introduce a GitHub configuration in CI if that is required.

**Comment by Betree** [comment]
@znarf introducing a Github token in CI may be cleaner than what I did in this PR (having specifics `if`s for the CI is not great). We need to make sure that it's a dummy token tho because we won't be able to protect it.

Let me know which option you prefer.

**Comment by znarf** [comment]
I wanted to create a new oAuth App and just use it for that. It will technically be a secret in GitHub, but yes it can be extracted with dedicated code and PR.

**Comment by Betree** [comment]
@znarf That works for me

**Comment by Betree** [comment]
@znarf can I merge this one to unblock the contributor (he's working on a bounty and is almost done), we can eventually follow up with the enhancement later?

**Comment by znarf** [comment]
@Betree ok

**Comment by Betree** [comment]
Closing in favor of https://github.com/opencollective/opencollective-api/pull/3680

**Pull request closed without merging**
