### PR TITLE
fix : 2675 : Re-organize API's tests

### PR DESCRIPTION
**Pull request by jeffin143**
Handles : https://github.com/opencollective/opencollective/issues/2675

### CODE REVIEW

**Comment by jeffin143** [comment]
@Betree : did you mean :- models.Conversations.test.js --> .Conversations.test.js

**Comment by Betree** [comment]
Hi @jeffin143, thanks for taking care of that.

Unfortunately issues with the `discussion` tag are things that didn't reach a consensus yet and that are not ready for implementation. In this particular case I'd like to handle it myself to also review the tests that we have and eventually extend the changes further than the specifications on the issue.

**Comment by jeffin143** [comment]
> Hi @jeffin143, thanks for taking care of that.
> 
> Unfortunately issues with the `discussion` tag are things that didn't reach a consensus yet and that are not ready for implementation. In this particular case I'd like to handle it myself to also review the tests that we have and eventually extend the changes further than the specifications on the issue.


No issues , I will go ahead and close this :)

**Comment by Betree** [comment]
Sorry for the lack of clarity, I'll be careful to self assign these issues until they reach a decision in the future.

**Comment by jeffin143** [comment]
> Sorry for the lack of clarity, I'll be careful to self assign these issues until they reach a decision in the future.

No  issues, I just overlooked the discussion label and went ahead

**Pull request closed without merging**
