### PR TITLE
Whitelist anchors for updates creation

### PR DESCRIPTION
**Pull request by Betree**
Whitelisted anchors:
- a
- h1
- h2
- strong
- img
- ul
- li

Fix for https://github.com/opencollective/frontend/issues/462

### CODE REVIEW

**Comment by HipsterBrown** [comment]
Thanks for creating a PR! :clap: The code looks good. I'll test it out locally and see if we have any test coverage we can add to that function.

**Comment by znarf** [comment]
@Betree Thank you, I'll check the DEBUG=email issue.

**Comment by HipsterBrown** [comment]
@Betree `strip_tags` appears to called in the `UpdateType` (`/server/graphql/types.js`) and parses the markdown text before being handled by the `createUpdate` function, so the `h1` and `h2` tags are stripped before your change. 

To fix that issue, I think it's fine to modify the `strip_tags` function to add `h1` and `h2` as default allowed tags. That change should also allow those tags after editing an update as well.

**Comment by HipsterBrown** [comment]
@Betree sorry about the delayed response. Those _should_ allowed by default in for the `sanitize-html` package (https://www.npmjs.com/package/sanitize-html#what-are-the-default-options).

**Comment by HipsterBrown** [comment]
@Betree any updates on this? Can you help with anything?

**Comment by Betree** [comment]
Hi @HipsterBrown, I'm still unable to connect with an account in dev - event with `DEBUG=email`. Maybe I missed something. I'd like to visually confirm that it works before pushing :wink:

**Comment by HipsterBrown** [comment]
@Betree Makes sense. 😄 Did you set the `DEBUG` environment variable in the `docker-compose.yml`, or somewhere else?

**Comment by Betree** [comment]
I just retried with setting DEBUG in `the docker-compose.yml` and it worked, I probably missed something the other day :wink: 

It now works as intended :
selection_495

Anyway the short resume from collective's homepage doesn't look very nice. Should we open another issue for this?

selection_496

**Comment by HipsterBrown** [comment]
@Betree Great work! 

> Anyway the short resume from collective's homepage doesn't look very nice. Should we open another issue for this?

Yes, can you create a separate issue for this bug? Then we can merge your work. :smile:

Do you have a Twitter we can mention when we thank you for this fix?

**Comment by Betree** [comment]
New issue in #1327. My twitter handle is @Betree83 :wink:

**Pull request merged**
