### PR TITLE
Add support to cancel recurring contributions when contributor is archived

### PR DESCRIPTION
**Pull request by SudharakaP**
Related to https://github.com/opencollective/opencollective/issues/6094

Front-end PR: https://github.com/opencollective/opencollective-frontend/pull/8353

### CODE REVIEW

**Comment by znarf** [comment]
I don't understand why we are using the Payee word here.

Isn't payee someone being paid, and usually used in the context of Expenses?

**Comment by Betree** [comment]
> I don't understand why we are using the Payee word here.
> 
> Isn't payee someone being paid, and usually used in the context of Expenses?

I agree, we rarely use the term in the context of financial contributions. The only related case I am aware of is in `server/graphql/common/transactions.ts`. For financial contributions, the payee would be the one receiving the money so; the collective.

Payer could work, but we probably want to simply say "contributor" here.

**Review by Betree — CHANGES_REQUESTED** [review]
This will only cancel Stripe, not PayPal. you can look at https://github.com/opencollective/opencollective-api/pull/8004 for an example of how it was implemented for a different use case.

**Comment by SudharakaP** [comment]
> This will only cancel Stripe, not PayPal. you can look at #8004 for an example of how it was implemented for a different use case.

Thanks. I've corrected this by changing the implementation. Only sad thing with this one is that it immediately cancels the subscription when the user archives. It would be nice if it only cancels in the next iteration. 🤔 

> I don't understand why we are using the Payee word here.
> 
> Isn't payee someone being paid, and usually used in the context of Expenses?

Agreed. I've removed this work and changed everything to "contributor"

**Comment by Betree** [comment]
> Only sad thing with this one is that it immediately cancels the subscription when the user archives. It would be nice if it only cancels in the next iteration. thinking

You mean on the next occurrence of the recurring contribution? I don't really agree, if I click on "Archive my account", get a modal saying "Your recurring contribution is going to be cancelled" and still click "Confirm", I expect my recurring contribution to be immediately cancelled - not in 1 year (in the case of a yearly contribution)

**Comment by Betree** [comment]
Assigning @hdiniz for the final review, he has a good understanding of the context around this issue

**Review by hdiniz — APPROVED** [review]

**Comment by SudharakaP** [comment]
> > Only sad thing with this one is that it immediately cancels the subscription when the user archives. It would be nice if it only cancels in the next iteration. thinking
> 
> You mean on the next occurrence of the recurring contribution? I don't really agree, if I click on "Archive my account", get a modal saying "Your recurring contribution is going to be cancelled" and still click "Confirm", I expect my recurring contribution to be immediately cancelled - not in 1 year (in the case of a yearly contribution)

Yeah that makes sense. 😄

**Pull request merged**
