### PR TITLE
Custom application email template for OCF

### PR DESCRIPTION
**Pull request by sreenidhithallam**
Resolve https://github.com/opencollective/opencollective/issues/6528

add: email template for OCF

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
Nice implementation! Could you share a screenshot of the email?

**Comment by sreenidhithallam** [comment]
> Nice implementation! Could you share a screenshot of the email?

Thanks, Attaching screenshot for reference.
Screenshot 2023-03-30 at 9 02 39 PM

**Review by Betree — APPROVED** [review]
Let's ship this, thank you @sreenidhithallam!

**Review by Betree — COMMENTED** [review]
It seems there's a prettier issue on `server/lib/email.ts`, @sreenidhithallam you can fix it by running `npm run prettier:fix`. I recommend enabling it by default on save in your IDE: https://www.educative.io/answers/how-to-set-up-prettier-and-automatic-formatting-on-vs-code

**Comment by sreenidhithallam** [comment]
> It seems there's a prettier issue on `server/lib/email.ts`, @sreenidhithallam you can fix it by running `npm run prettier:fix`. I recommend enabling it by default on save in your IDE: https://www.educative.io/answers/how-to-set-up-prettier-and-automatic-formatting-on-vs-code

Fixed it @Betree  Thanks

**Review by Betree — APPROVED** [review]
Perfect @sreenidhithallam, thanks for iterating. The remaining failing tests are CI issues related to the fact we're running on a fork. We'll invite you to https://github.com/orgs/opencollective/teams/contributors/members after merging this PR, you'll be able to push directly to our main repo (except protected branches) if you ever want to contribute again.

Thanks again!

**Pull request merged**
