### PR TITLE
Fix ValidationError when slug clashes with existing deleted one.

### PR DESCRIPTION
**Pull request by kewitz**
This is enforced either way through index.

### CODE REVIEW

**Comment by Betree** [comment]
Nice, it would be great to better display sql errors but this fix does the job

**Comment by znarf** [comment]
@kewitz Could you audit the codebase and find similar occurrences?

**Comment by znarf** [comment]
Also note that when we delete accounts using the normal path, we're already making sure to free the slug, see `deleteCollective` in GraphQL v1.

**Comment by kewitz** [comment]
@znarf, nice catch! So this is really an edge-case... should we just hard-delete test-collective?

**Comment by znarf** [comment]
We should make sure to free all the slug of soft deleted collectives.

**Comment by kewitz** [comment]
Actually, we shouldn't solve it like this.
No point in include deleted rows in the query since it will be an ever-increasing complexity to process.
This is a super-edge case, I'll make sure we're freeing up slugs and write a migration to free-up soft-deleted sluges.

**Comment by kewitz** [comment]
@Betree since our policy is to not hard delete collectives, I don't like to have an ever-increasing query tied to the onboard flow.
Also, in the case of us failing to validate the existing collectives, the unique validator will throw and we'll be able to properly display the Sequelize validation error in the frontend.

**Pull request closed without merging**
