### PR TITLE
make sure the hostFeePercent matches the hostFeePercent of the host

### PR DESCRIPTION
**Pull request by xdamman**
Fixes https://github.com/opencollective/opencollective/issues/2000

### CODE REVIEW

**Comment by znarf** [comment]
@xdamman have you thought about running a migration to update the past entries?

**Comment by znarf** [comment]
@xdamman Have you seen my comment? What's needed to complete this and merge?

**Comment by xdamman** [comment]
I've seen your comment but I don't have the time to write such migration.
It's not straightforward. I've computed what each host needs to reimburse on the issue. I think it's good enough. 
It's more important to make sure we don't have that issue again in the future so let's merge and deploy this.

**Comment by znarf** [comment]
So, let's say we merge that. How do we ensure that `hostFeePercent` is the right one in the database?

**Comment by xdamman** [comment]
As documented in the issue, I already ran the query to update those `hostFeePercent` for two main hosts that were impacted, I can do it for the remaining ones once deployed.

**Comment by znarf** [comment]
Running that automatically as a migration is the way to do it. No need to sync as a team, the query can be reviewed in the PR and it's executed exactly at the right time.

**Comment by znarf** [comment]
@xdamman Slow feedback loop here :-/ Merging to avoid issues for future collectives. Please make sure the database is updated after deploy. Still think it would have been cleaner with a simple migration.

**Pull request merged**
