### PR TITLE
Refactoring db_copy_to_localost script to use shared functionality with db_restore

### PR DESCRIPTION
**Pull request by iamliamc**
Resolve https://github.com/opencollective/opencollective/issues/6194

### CODE REVIEW

**Comment by iamliamc** [comment]
This is a harder one for me to test locally due to:
```
➜  api git:(main) ✗ npm run db:copy:prod

> db:copy:prod
> ./scripts/db_copy_to_localhost.sh prod && PG_DATABASE=opencollective_prod_snapshot npm run db:sanitize

heroku: Press any key to open up the browser to login or q to exit: 
Opening browser to https://cli-auth.heroku.com/auth/cli/browser/640ff464-85c3-43c6-8d57-8ef2a40f1fbf?requestor=SFMyNTY.g2gDbQAAAAw2OC4zMi4xNDYuNDduBgCoFr9phQFiAAFRgA.1euBigfMmkd16gcUhpPKs4CE_tLpRmgRvNWbRcVlgsQ
Logging in... done
 ›   Error: You do not have permission to view config vars on opencollective-prod-api. You need to have the deploy or operate permission on this app.
 ›
 ›   Error ID: forbidden
 ```

**Review by Betree — APPROVED** [review]
@iamliamc thank you, your changes worked perfectly! While testing, I noticed a few things that could be improved with the script and took the liberty of adding the changes to your PR. They're mostly:
1. Add a `--use-postgis` flag: depending on the DB you're restoring, you may need that as historically our DB used to have this extension.
2. Make sure to use the postgis flag when restoring a prod or staging DB
3. Make sure dump file has the env in its name (staging|prod)
4. Fix a bug in `scripts/db_restore.sh` where the last argument was not considered

**Comment by Betree** [comment]
@iamliamc Some tests are not passing because we're on a fork, but everything's good and ready to merge. We'll make that live on Monday. I've added you to https://github.com/orgs/opencollective/teams/contributors/members, you'll be able to push directly to our main repositories if you ever want to contribute again :slightly_smiling_face:

**Comment by iamliamc** [comment]
> @iamliamc Some tests are not passing because we're on a fork, but everything's good and ready to merge. We'll make that live on Monday. I've added you to https://github.com/orgs/opencollective/teams/contributors/members, you'll be able to push directly to our main repositories if you ever want to contribute again 🙂

Ah great! I won't try to keep updating on `main` and causing CI to run! Thanks for the note :)

**Pull request merged**
