### PR TITLE
Change Virtual Card Purchase Email Link to Edit the Expense

### PR DESCRIPTION
**Pull request by SudharakaP**
Resolve https://github.com/opencollective/opencollective/issues/6046

image

### CODE REVIEW

**Comment by SudharakaP** [comment]
@alanna : Does the new wording change here looks good? Let me know if you like to make any further changes here. 😄

**Comment by alanna** [comment]
looks good to me!

**Review by znarf — COMMENTED** [review]
Can you share a screenshot of the rendering? There may be mistakes in the template.

**Comment by znarf** [comment]
We can tackle in a follow up issue, but it's technically not true that the card was charged, at this stage it's just an authorization. Maybe it will be charged, maybe it will be cancelled. The amount may change.

Also, people don't have necessarily a receipt at this point so we should not be too aggressive trying to collect the receipt. This is why we have the other email when the transaction is confirmed.

**Comment by alanna** [comment]
It's fine if they don't upload the receipt at this step, but if they do have it, we should make it easy for them, as they are in the mindset of completing the process and it's fresh in their mind.

**Comment by znarf** [comment]
I liked in the previous copy that we were saying "upload a receipt **if you already have one**"

To be clear, my feedback is not blocking here.

**Comment by alanna** [comment]
Oh yeah that extra phrase sounds fine

**Comment by SudharakaP** [comment]
> Can you share a screenshot of the rendering? There may be mistakes in the template.

I've added a screenshot. And also added a template test to `compile-email.js` for this. 

> I liked in the previous copy that we were saying "upload a receipt **if you already have one**"
> 
> (To be clear, my feedback is not blocking here.)

That makes sense; I've re-added the "upload a receipt **if you already have one**" phrase back.

**Comment by SudharakaP** [comment]
@znarf @alanna : Could you take a look once more as I've changed the template and verify everything looks good to merge?

**Pull request merged**
