### PR TITLE
Keep ExpenseId in its refund transactions

### PR DESCRIPTION
**Pull request by kewitz**
For debugging reasons.

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
Should we update existing transactions for data consistency? (or create an issue to do it later)

**Review by znarf — APPROVED** [review]

**Comment by znarf** [comment]
Would be a nice touch to migrate past issues or to document the problem in an issue at least.

**Comment by kewitz** [comment]
@Betree @znarf I'll add a migration to this PR.

**Review by Betree — APPROVED** [review]
The migration looks good!

**Pull request merged**
