### PR TITLE
Add section about funding.yml in GitHub Signup email

### PR DESCRIPTION
**Pull request by piamancini**
@znarf Is there any way I can test this email on staging or see a preview?

### CODE REVIEW

**Comment by znarf** [comment]
@piamancini Screenshot_2019-08-23 Screenshot

**Comment by piamancini** [comment]
ah, duh. 
sorry just fixed it.

**Comment by znarf** [comment]
@piamancini new version

Screenshot_2019-08-27 Screenshot

**Comment by piamancini** [comment]
thanks, just made an update to the copy. Paragraph was too long.

**Comment by piamancini** [comment]
@znarf did I mess up something?

**Comment by znarf** [comment]
@piamancini no, random failure

**Comment by znarf** [comment]
Screenshot_2019-08-27 Screenshot(1)

**Comment by znarf** [comment]
Screenshot_2019-08-27 Screenshot(2)

**Comment by piamancini** [comment]
LGTM - we can ship that 
thanks!

**Pull request merged**
