### PR TITLE
Rename Subcollective to Relatedcollective

### PR DESCRIPTION
**Pull request by SudharakaP**
This changes `SUB_COLLECTIVE` to `RELATED_COLLECTIVE` through a migration script

Related to https://github.com/opencollective/opencollective/issues/3040

### CODE REVIEW

**Comment by znarf** [comment]
Please push directly to this repository next time so E2E tests get triggered.

**Comment by Betree** [comment]
We're still waiting for feedback on https://github.com/opencollective/opencollective/issues/3040 before we can merge

**Comment by Betree** [comment]
As per https://github.com/opencollective/opencollective/issues/3040#issuecomment-620533323, let's rather say "Connected collectives".

**Comment by SudharakaP** [comment]
> As per [opencollective/opencollective#3040 (comment)](https://github.com/opencollective/opencollective/issues/3040#issuecomment-620533323), let's rather say "Connected collectives".

Done. :smile:

> Please push directly to this repository next time so E2E tests get triggered.

@znarf @Betree : I see that the end to end tests are only triggered on push. Just wondering why don't we enable it on pull requests as well? :thinking:

**Comment by znarf** [comment]
@SudharakaP our E2E CI is relying on a "Matching Branch" functionality that is only possible on push, not on PR events.

**Comment by SudharakaP** [comment]
@znarf : Got it; so basically if I am understanding correctly, we need to create branches on the repo itself not on the fork correct? In other words clone, instead of forking. :smile:

**Comment by Betree** [comment]
@SudharakaP could you rebase this PR on master? I think E2e tests are not passing because you're on an older version of the API.

**Comment by SudharakaP** [comment]
> @SudharakaP could you rebase this PR on master? I think E2e tests are not passing because you're on an older version of the API.

Done. Hope that will solve the problem. :thinking:

**Comment by Betree** [comment]
> Done. Hope that will solve the problem.

It did, thanks @SudharakaP :slightly_smiling_face: 

Merging & deploying now!

**Comment by SudharakaP** [comment]
> > Done. Hope that will solve the problem.
> 
> It did, thanks @SudharakaP slightly_smiling_face
> 
> Merging & deploying now!

You are welcome :+1:

**Pull request merged**
