### PR TITLE
fix(server/constants/currencies.ts): delete currencies constants in f…

### PR DESCRIPTION
**Pull request by NotJohs**
…avour of currencies util in lib

Re [#1662](https://github.com/opencollective/opencollective/issues/1662)

### CODE REVIEW

**Comment by znarf** [comment]
@NotJohs can you push to our repository `git@github.com:opencollective/opencollective-api.git` and issue a PR from here, it's easier for us.

**Comment by NotJohs** [comment]
@znarf Alright, directly to master?

**Comment by maddhruv** [comment]
> Alright, directly to master?

no no no, we don't push to `master` and even though `master` would be a protected branch i.e. you can't push directly to it.

create this branch `fix/delete-currency-fxrate` directly on this repository, push and then raise a pull request to `master`

**Comment by NotJohs** [comment]
Alright, Thanks @maddhruv

**Pull request closed without merging**
