### PR TITLE
feat(tiers): track Tier History

### PR DESCRIPTION
**Pull request by NotJohs**
Used Historical from sequelize-historical to track tier history

re [#2114](https://github.com/opencollective/opencollective/issues/2114)

### CODE REVIEW

**Comment by znarf** [comment]
When editing the Tiers from the frontend, it's failing.

Capture d’écran 2019-09-16 à 09 57 29

If you look at the migrations folder, you will see that every time we added history to a table, we pro-actively created the table. ie: https://github.com/opencollective/opencollective-api/blob/cc567ab1cbe0e33ad8c2f6965977b4caf6f94351/migrations/20160613174610-temporal-migration.js

**Comment by NotJohs** [comment]
@znarf keep on having this nasty error with no helpful description.
Screenshot 2019-09-18 at 7 01 21 PM

**Comment by znarf** [comment]
@NotJohs Thank you for the update, looks good! Will test tomorrow.

**Comment by NotJohs** [comment]
@znarf Great. Thanks

**Pull request closed without merging**
