### PR TITLE
Update expense invalid link in collective expense approved email template

### PR DESCRIPTION
**Pull request by flickz**
This PR fix the invalid expense link pointed out in [#1675 ](https://github.com/opencollective/opencollective/issues/1675)

cc @Betree

### CODE REVIEW

**Comment by Betree** [comment]
Looks good to me too, there's a second link that needs to be fixed in the same way at line 10:

https://github.com/opencollective/opencollective-api/pull/1687/files#diff-c831a643d5338fda0d93a367bc5b8f43R10

**Comment by flickz** [comment]
Fixed!

**Comment by znarf** [comment]
@Betree Just wondering, why do we need that fix when the route is the following:
`/:parentCollectiveSlug?/:collectiveType(events)?/:collectiveSlug/expenses/:filter(categories|recipients)?/:value?`

**Comment by Betree** [comment]
@znarf Previous links were pointing to `/expenses/____`. In the route you mention above, having the collective slug before `/expenses` is mandatory.

**Pull request merged**
