### PR TITLE
Update `ics` package to latest version: v2.29.0

### PR DESCRIPTION
**Pull request by SudharakaP**
This updates the `ics` package to the latest version. It seems that the `ics.createEvent` function now takes dates as arrays instead of `moment` objects. 🤔 

Related to https://github.com/opencollective/opencollective-api/pull/6212

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
I don't get it, there is no update to `package.json` and the `package-lock.json` update seems unrelated. Did you forget to commit them?

Also, I don't see this change listed on https://github.com/adamgibbons/ics/releases, is the change documented somewhere?

Did you try the update to make sure the ICS file was properly formatted?

**Comment by SudharakaP** [comment]
@Betree : 

> I don't get it, there is no update to `package.json` and the `package-lock.json` update seems unrelated. Did you forget to commit them?

Ops, I think I somehow missed to commit those. I've corrected it. Thanks much for pointing it out. 👍🏽 

> Also, I don't see this change listed on https://github.com/adamgibbons/ics/releases, is the change documented somewhere?

Yes I didn't see either, but if you notice their [readme](https://github.com/adamgibbons/ics/blob/master/README.md), it seems to use the array format for dates. 

> Did you try the update to make sure the ICS file was properly formatted?

Yes. Here's a sample file which I've generated. 

```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:adamgibbons/ics
METHOD:PUBLISH
X-PUBLISHED-TTL:PT1H
BEGIN:VEVENT
UID:49d51e21-82f4-488c-b020-0a18db01b0d9
SUMMARY:Test Agora Event
DTSTAMP:20210722T152300Z
DTSTART:19691202T000000Z
DTEND:20210622T131700Z
URL:http://localhost:3000/agora-collective/events/test-agora-event-73de3f3d
STATUS:CONFIRMED
ORGANIZER;CN=Agora Collective:mailto:no-reply@agora-collective.opencollecti
	ve.com
BEGIN:VALARM
ACTION:AUDIO
REPEAT:2
ATTACH;VALUE=URI:Glass
TRIGGER:-PT24H
END:VALARM
BEGIN:VALARM
ACTION:AUDIO
REPEAT:2
ATTACH;VALUE=URI:Glass
TRIGGER:-PT72H
END:VALARM
END:VEVENT
END:VCALENDAR
```

**Review by Betree — APPROVED** [review]
> Yes. Here's a sample file which I've generated.

Great, if these timestamps match the event dates I'm all good with this update!

**Comment by SudharakaP** [comment]
> > Yes. Here's a sample file which I've generated.
> 
> Great, if these timestamps match the event dates I'm all good with this update!

Thanks, I've created an issue on that repo as well just to double check and maybe add it to the documentation; https://github.com/adamgibbons/ics/issues/190. 😸

**Comment by znarf** [comment]
The month is wrong. For an event in October, it's displayed September. Can that be fixed?

**Comment by SudharakaP** [comment]
> The month is wrong. For an event in October, it's displayed September. Can that be fixed?

@znarf : Fixed at https://github.com/opencollective/opencollective-api/pull/6462. Let me know how it looks.

**Pull request merged**
