### PR TITLE
Remove `setupModel` calls

### PR DESCRIPTION
**Pull request by Betree**
While looking at a model, I realized Typescript was missing some errors; it somehow failed to infer the type from inside the function, probably because the argument passed to `setupModel` (the model itself) was not typed.

I figured that, since we have `.git-blame-ignore-revs` now, we could get rid of them and ignore the commit in the history.

This is best reviewed with "Ignore whitespace changes": https://github.com/opencollective/opencollective-api/pull/7814/files?diff=split&w=1

### CODE REVIEW

**Comment by Betree** [comment]
@znarf I'll wait for your feedback before merging this one

**Comment by znarf** [comment]
Ok, but we should. not squash and merge right ?

I also saw that it's possible to add comments in the `.git-blame-ignore-revs`, that could be useful?

**Comment by Betree** [comment]
> Ok, but we should. not squash and merge right ?
Indeed

> I also saw that it's possible to add comments in the `.git-blame-ignore-revs`, that could be useful?
Adding one now

**Review by znarf — APPROVED** [review]

**Comment by Betree** [comment]
Rebased

**Pull request merged**
