### PR TITLE
enhancement: send notification to all admins of collective

### PR DESCRIPTION
**Pull request by snitin315**
Resolve https://github.com/opencollective/opencollective/issues/4559

Following are some corresponding screenshots for a collective with two admins.

Screenshot 2021-08-20 at 8 17 46 AM
Screenshot 2021-08-20 at 8 21 39 AM
Screenshot 2021-08-20 at 8 21 49 AM

### CODE REVIEW

**Comment by snitin315** [comment]
WIP on tests.

**Review by znarf — COMMENTED** [review]
Regarding the tests, I think we want to keep the email mock, but adapt it to the new behavior.

notifyAdminsOfCollective ultimately trigger the email library through (notifySubscribers)

**Comment by snitin315** [comment]
Ready for review.

**Review by znarf — COMMENTED** [review]
Looks good. Because of timing, I don't want to merge and deploy this today. It's tomorrow the 1st of the month and we're gonna send a lot of those emails, minimizing the risk if something is not right.

Maybe on Thursday.

**Comment by snitin315** [comment]
@znarf it should be safe to merge now.

**Comment by Betree** [comment]
Rebased and added https://github.com/opencollective/opencollective-api/pull/6465/commits/43879207af43db3a3c979e33abe9f11e58f4412c to fix a regression that prevented thank you emails from being sent to incognito profiles.

**Comment by znarf** [comment]
Rebased.

**Comment by snitin315** [comment]
Thanks for the rebase and update.

**Comment by znarf** [comment]
@snitin315 thank you for your patience, we'll tentatively merge and deploy this tomorrow.

**Pull request merged**
