### PR TITLE
Allow deletion of virtual card by collective admin

### PR DESCRIPTION
**Pull request by hdiniz**
Related https://github.com/opencollective/opencollective/issues/5991
Frontend https://github.com/opencollective/opencollective-frontend/pull/8253

### CODE REVIEW

**Review by znarf — APPROVED** [review]
Looks good to me.

**Comment by znarf** [comment]
No modification to the frontend to allow this?

**Comment by hdiniz** [comment]
> No modification to the frontend to allow this?
Yes, I forgot to publish the PR:
https://github.com/opencollective/opencollective-frontend/pull/8253

**Review by Betree — APPROVED** [review]
Lgtm!

**Pull request merged**
