### PR TITLE
Remove CommentReactionMutations.js

### PR DESCRIPTION
**Pull request by SudharakaP**
Resolve https://github.com/opencollective/opencollective/issues/4393. 

Since we now use `emojiReactionMutations` in favour of `commentReactionMutations`, we should remove the comment reaction mutations. 😄 🐨

### CODE REVIEW

**Review by Betree — APPROVED** [review]
All good, let's wait for the feature to be fully deployed on prod before merging this. Could also be nice to update the GQL files, but not mandatory.

**Comment by SudharakaP** [comment]
> All good, let's wait for the feature to be fully deployed on prod before merging this. It could also be nice to update the GQL files, but not mandatory.

Thanks. I've just updated the GQL files as well. 😄

**Comment by SudharakaP** [comment]
@Betree : I'll be merging this one if no objections given that we have now merged the new emoji reaction mutations. 😄

**Review by Betree — APPROVED** [review]
Sounds good :+1:

**Pull request merged**
