### PR TITLE
Remove Google Analytics keywords from urls

### PR DESCRIPTION
**Pull request by SudharakaP**
Resolve https://github.com/opencollective/opencollective/issues/4555

slack-connect

### CODE REVIEW

**Review by znarf — APPROVED** [review]
Looks good. Let's wait for the tests to complete.

**Comment by znarf** [comment]
One test seems to be failing.

**Comment by SudharakaP** [comment]
> One test seems to be failing.

Taking a look at that. 🤔  👍🏽

**Comment by SudharakaP** [comment]
Fixed the test. Will be merging this soon if no objections.

**Pull request merged**
