### PR TITLE
feat(ocf-application): allow existing collective admin to apply to OCF host

### PR DESCRIPTION
**Pull request by flickz**
Following up https://github.com/opencollective/opencollective-frontend/pull/5833 on the recent [update](https://github.com/opencollective/opencollective/issues/3683#issuecomment-769566325) to OCF onboarding flow, this PR allows authenticated admin of existing collective to apply to Open collective foundation.

### CODE REVIEW

**Comment by znarf** [comment]
Sorry, but I dislike the approach.

The `createCollective` mutation is about creating a collective and not applying with an existing collective.

We should apply with a dedicated mutation. @Betree do you have a suggestion how best to handle this?

**Comment by Betree** [comment]
> Sorry, but I dislike the approach.
> 
> The `createCollective` mutation is about creating a collective and not applying with an existing collective.
> 
> We should apply with a dedicated mutation. @Betree do you have a suggestion how best to handle this?

I agree. We have an `applyToHost` mutation on V2 that should do the job just fine, we just need to add the `applicationData` there

**Review by znarf — APPROVED** [review]
Looks good.

**Review by Betree — APPROVED** [review]
:+1:

**Pull request merged**
