### PR TITLE
add repo stars data in update-contributions script; closes #452

### LINKED ISSUE #452: pull more data in update-contributions script
see opencollective/opencollective#135 for original issue, and related opencollective/opencollective-jobs#2 

Just creating this as a reference to track my work in this repo.  see #387

### PR DESCRIPTION
**Pull request by boneskull**
- also update opencollective-jobs

addresses opencollective/opencollective#135

### CODE REVIEW

**Comment by xdamman** [comment]
What would `data.repos` look like?
Can you add a total count of stars across all repos in `group.data.stars` ?
The goal is to be able to easily order the collectives we have.

**Comment by boneskull** [comment]
This would be a simple `reduce()` call which would create a sum of all stars.  This would happen after line 44 in `update-contributions.js`, as in this PR.

**Comment by boneskull** [comment]
(I cannot commit any time to these issues until at least 6/25)

**Comment by asood123** [comment]
Merging this for now because I want to update other things in the script and don't want to cause merge mess.

**Comment by asood123** [comment]
Added support for stars here: https://github.com/OpenCollective/opencollective-api/pull/467

**Pull request merged**
