### PR TITLE
Fix broken tiers

### PR DESCRIPTION
**Pull request by flickz**

### CODE REVIEW

**Comment by znarf** [comment]
Let's double/triple check that.

This could be a case where trying to fix it will actually introduce a functional regression.

**Comment by znarf** [comment]
So, let's remove that and edit the code at https://github.com/opencollective/opencollective-api/blob/master/server/models/Collective.js#L72 to make sure it works as expected (title, description, defaults).

We'll first need to check with @alannallama and @piamancini what should exactly be the default tiers from now.

**Comment by alannallama** [comment]
@znarf sorry I just saw this. Are you still waiting on info from us for this?

**Comment by znarf** [comment]
@alannallama The question is: are you currently happy with the default tiers for the Open Source Collectives?

**Pull request merged**
