### PR TITLE
Add private instructions on event ICS file

### PR DESCRIPTION
**Pull request by Betree**
Example file: https://drive.google.com/file/d/1EkEYP9As8leWa-o9RJR6yD7n6_YsqD1j/view?usp=sharing

### CODE REVIEW

**Comment by RichardLitt** [comment]
This looks good to me from just looking at the code.

**Review by RichardLitt — COMMENTED** [review]
Perhaps there should also be a note saying that "this is private instructions". Something like: 

```
          description += `\n\n<b>Private instructions:</b>\n\n${this.data.privateInstructions}`;
```

**Comment by Betree** [comment]
> \n\n<b>Private instructions:</b>\n\n$

Done, though I removed the HTML part as I was getting inconsistent results between Calendar clients (even when using the `htmlContent` prop from https://www.npmjs.com/package/ics) that I was not ready to investigate deeper.

**Review by RichardLitt — APPROVED** [review]

**Comment by RichardLitt** [comment]
Thank you, @Betree!

**Pull request merged**
