### PR TITLE
update email

### PR DESCRIPTION
**Pull request by piamancini**
removed 'pending approval'. We'll accept open source collectives straight away

### CODE REVIEW

**Comment by xdamman** [comment]
Waiting to merge this as sending the PR is still not fully automated

**Comment by asood123** [comment]
Do we need to wait for that? Even if that happens a couple of days after,
it's better to unblock github flow signups immediately and let them start
raising money.

**Comment by xdamman** [comment]
I like the idea of having them review and merge the pull request as part of the flow to activate their collective. Also we say in the default tiers that sponsors' logo would show on their GitHub readme.

**Comment by asood123** [comment]
completed in a different PR

**Pull request closed without merging**
