### PR TITLE
Revert dependabot to previous version

### PR DESCRIPTION
**Pull request by znarf**

### CODE REVIEW

**Comment by SudharakaP** [comment]
@znarf : We need to change the `ci.yml` as well to remove the lines; `if: ${{ github.actor != 'dependabot[bot]' }}`; https://github.com/opencollective/opencollective-api/blob/31bf5fee3fd56aa4fd99a121170d37901ecce42f/.github/workflows/ci.yml#L25

**Review by SudharakaP — CHANGES_REQUESTED** [review]
@znarf : We need to change the `ci.yml` as well to remove the lines; `if: ${{ github.actor != 'dependabot[bot]' }}`; https://github.com/opencollective/opencollective-api/blob/31bf5fee3fd56aa4fd99a121170d37901ecce42f/.github/workflows/ci.yml#L25

Also should remove the file `ci-dep-updates.yml

**Comment by znarf** [comment]
@SudharakaP done

**Comment by SudharakaP** [comment]
> @SudharakaP done

@znarf : There were more `if` conditions; so I've pushed a change the removes them.

**Pull request merged**
