### PR TITLE
added user.description and user.isOrganization

### PR DESCRIPTION
**Pull request by xdamman**

### CODE REVIEW

**Comment by asood123** [comment]
Need to add a migration file or it'll croak in production

**Comment by xdamman** [comment]
What do you mean by that? This is just adding new columns so there shouldn't be any migration involved.

**Comment by asood123** [comment]
Given how so many people work on the code base, I think in general we
shouldn't let the model diverge from the underlying database. Is there a
reason not to do the migration at the same time?

**Comment by xdamman** [comment]
Doh, I forgot to add the migration file. Done.

**Pull request merged**
