### PR TITLE
Fix Monthly Platform Report

### PR DESCRIPTION
**Pull request by kewitz**
The problem is that we were missing platform fees from bank transfers.
image

### CODE REVIEW

**Comment by znarf** [comment]
Doesn't seem to be it. No reason to have "Fees On Top" in "Manually Added Funds" right?

Screenshot 2020-08-19 at 10 58 09

**Comment by kewitz** [comment]
@znarf yep, this is actually related to bank transfers but I'm still investigating. I want to make these queries are MECE.

**Comment by znarf** [comment]
@kewitz No platform fees for Bank Transfers?

**Comment by kewitz** [comment]
@znarf good catch.
We recently had a small discussion on our channel about that with Pia, we're currently not collecting those.
Should I include it anyway in this report?

**Comment by znarf** [comment]
@kewitz We have one significant transaction in July for the OSC host (id: 493199) and I'm working on the long term implementation.

Yes, we need to track it.

**Pull request merged**
