### PR TITLE
Knox Replacement with Aws-Sdk

### PR DESCRIPTION
**Pull request by vickywane**
Replacement for knox with aws-sdk

### CODE REVIEW

**Comment by znarf** [comment]
Early feedback after CI was triggered.

- all tests failed because `package-lock.json` was not updated
- please also make sure your code is formatted with lint and prettier, some tips here: https://github.com/opencollective/opencollective-frontend/blob/master/CONTRIBUTING.md

**Comment by vickywane** [comment]
I'll make the needed changes and let's see if we can merge successfully without closing this PR

**Comment by vickywane** [comment]
Can also update the node version?  
I hope it won't break anything !!

**Comment by znarf** [comment]
@vickywane no, updating the node version is not in the scope of this PR. Why would that be necessary?

**Comment by vickywane** [comment]
Alright.  I was running a higher node version in dev environment.  

I'll make use of nvm to run a separate version

**Comment by vickywane** [comment]
Looking at the snapshot of the Travis break I saw something with regards to test.  
Was any test written using the Knox library ?
@francois

**Comment by znarf** [comment]
@vickywane We don't have Travis. Are you talking about CircleCI?

Have you taken in consideration my previous comments? https://github.com/opencollective/opencollective-api/pull/1847#issuecomment-478745021 That would be a nice step forward, but I don't see any new commit in the branch.

There is one test that is relevant: `images.routes.test.js`. You can run it with `npx babel-node test/images.routes.test.js`.

**Pull request closed without merging**
