### PR TITLE
fix 'Unhandled rejection SequelizeDatabaseError' error messages

### PR DESCRIPTION
**Pull request by EslamHiko**
This PR fixes : https://github.com/opencollective/opencollective/issues/2607
References : https://sequelize.org/master/class/lib/model.js~Model.html (Schema Section) , https://stackoverflow.com/questions/39580973/node-js-defining-postgres-schemas-in-sequelize/39581304#39581304

Before : 
before

After:
after

### CODE REVIEW

**Comment by znarf** [comment]
Great, thank you!

- Why do we need to do that for these specific tables? Not all?
- When is Sequelize precisely creating the tables in this case?

**Comment by EslamHiko** [comment]
- Why do we need to do that for these specific tables? Not all? : I think we can do this for all the other tables, I didn't want to modify unnecessary tables.
I did this for these specific tables because after I did it only for `Transaction` model `Collectives` and `Transactions` Errors disappeared but 'Notifications', `Members` and `PaymentMethods` Errors appeared. The strange thing, I tried solving `Members` error by modifying `Member` model but the error didn't disappear until I did this for `User` Model.

- When is Sequelize precisely creating the tables in this case? : Sequelize creates tables when the model trigger `create` function ref: https://stackoverflow.com/a/52267740.

**Comment by znarf** [comment]
> I think we can do this for all the other tables

I think we should do it as as matter of consistency. Is it possible that there is a single command to do that?

> When is Sequelize precisely creating the tables in this case?

I found that we're reseting the schema quite often in the tests: https://github.com/opencollective/opencollective-api/blob/master/test/utils.js#L47 This is when we're creating and re-creating the tables I think.

**Comment by EslamHiko** [comment]
- I think we should do it as as matter of consistency. Is it possible that there is a single command to do that? : I tried to add `schema: 'public'` here https://github.com/opencollective/opencollective-api/blob/master/server/models/index.js#L56 but this error showed up `Couldn't recreate the schema`.

**Pull request merged**
