### PR TITLE
CI: update setup

### PR DESCRIPTION
**Pull request by znarf**
- use `opencollective` instead of `ubuntu` user

### CODE REVIEW

**Comment by eloyekunle** [comment]
@znarf Seems this also needs to be done in the frontend.

**Comment by znarf** [comment]
@eloyekunle it was done and merged at the same time: https://github.com/opencollective/opencollective-frontend/pull/1808

**Comment by eloyekunle** [comment]
I'm getting a CI error here: https://circleci.com/gh/opencollective/opencollective-frontend/21574

**Comment by znarf** [comment]
@eloyekunle It's because the matching API branch was not updated. We should deleted it instead.

**Comment by eloyekunle** [comment]
Oh okay, will do that. Thanks.

**Pull request merged**
