### PR TITLE
interval can be month, year or null

### PR DESCRIPTION
**Pull request by xdamman**
necessary for https://github.com/OpenCollective/opencollective-website/pull/627

### CODE REVIEW

**Comment by xdamman** [comment]
Actually, I just found out that everywhere in the database we use `{"interval":"one-time"}` or `{"interval":"monthly"}`.
So instead, I should rather standardize on that and not on `month / year / null`. So ignore this PR.

**Comment by xdamman** [comment]
To be more accurate, the API expects the interval in the tier definition to be `monthly`, `yearly` or `one-time`, but the `Subscriptions` model, expects the interval to be `month`, `year` or `null` :-/

**Comment by xdamman** [comment]
If we want to standardize everything to month/year/null, we would have to do a query in the DB to update all the tiers in the Groups table.

If we want to standardize everything to monthly/yearly/one-time, we would just have to run a migration on the `Subscriptions` table (I'd personally prefer the latter as it sounds more natural to have `monthly` imho)

**Comment by xdamman** [comment]
@asood123 any strong feelings about this?

I think we can table this for now, no urgency. Just wanted to make sure you saw this.
Feel free to close this issue for now.

**Comment by asood123** [comment]
Fine with tabling. We can come back to it later.

**Pull request closed without merging**
