### PR TITLE
Don't show changelog update notification to new users

### PR DESCRIPTION
**Pull request by SudharakaP**
Resolve https://github.com/opencollective/opencollective/issues/4435

new-user

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
Now that I see this, I realize that this approach has a few downsides:
- Having `null` has a default value here makes it clear & easy to track the changelog opening percentage. It's kind of false to say that they viewed the changelog on this date when they have not.
- To make this work, we'd need to adapt things for guest users. Guest users create an account when they contribute, but they often login only weeks or months later. This first sign-in should be the date used to compare against changelog.

Editing `hasSeenLatestChangelogEntry` seems simpler. We should use `user.confirmedAt` for our checks. Something as simple as:

```es6
export const hasSeenLatestChangelogEntry = (...) => {
  // Add a comment here to explain why we're doing that
  const userChangelogViewDate = user.changelogViewDate || user.confirmedAt || user.createdAt;

  (...)
}
```

**Comment by SudharakaP** [comment]
> Now that I see this, I realize that this approach has a few downsides:
> 
>     * Having `null` has a default value here makes it clear & easy to track the changelog opening percentage. It's kind of false to say that they viewed the changelog on this date when they have not.
> 
>     * To make this work, we'd need to adapt things for guest users. Guest users create an account when they contribute, but they often login only weeks or months later. This first sign-in should be the date used to compare against changelog.

@Betree : Agree, I've adjusted the code based on your suggestion. 😄

**Review by Betree — APPROVED** [review]
Lgtm :+1: The previous version of the code assumed that `user` could be null, but if that's not breaking anything I'm all good.

**Comment by SudharakaP** [comment]
> Lgtm +1 The previous version of the code assumed that `user` could be null, but if that's not breaking anything I'm all good.

@Betree : Thanks. No it seems to work fine without the null check. So I think it's fine. 😄

**Pull request merged**
