### PR TITLE
HostReports: Time series metric

### PR DESCRIPTION
**Pull request by Betree**
For https://github.com/opencollective/opencollective/issues/4606

**Example query**
```gql
{
  host(slug: "opensourceorg") {
    hostMetricsTimeSeries(startDate: "2021-01-01T00:00:00Z", endDate: "2022-01-01T00:00:00Z", timeUnit: MONTH) {
      platformTips {
        startDate
        endDate
        timeUnit
        nodes {
          date
          amount {
            value
            currency
          }
        }
      }
    }
  }
}
```

**Result**
```json
{
  "data": {
    "host": {
      "hostMetricsTimeSeries": {
        "platformTips": {
          "startDate": "2021-01-01T00:00:00.000Z",
          "endDate": "2022-01-01T00:00:00.000Z",
          "timeUnit": "MONTH",
          "nodes": [
            {
              "date": "2021-05-01T00:00:00.000Z",
              "amount": {
                "value": 91.2,
                "currency": "USD"
              }
            },
            {
              "date": "2021-06-01T00:00:00.000Z",
              "amount": {
                "value": 6,
                "currency": "USD"
              }
            },
            {
              "date": "2021-07-01T00:00:00.000Z",
              "amount": {
                "value": 12,
                "currency": "USD"
              }
            },
            {
              "date": "2021-08-01T00:00:00.000Z",
              "amount": {
                "value": 13.5,
                "currency": "USD"
              }
            },
            {
              "date": "2021-09-01T00:00:00.000Z",
              "amount": {
                "value": 27.75,
                "currency": "USD"
              }
            }
          ]
        }
      }
    }
  }
}
```

### CODE REVIEW

**Comment by znarf** [comment]
Looks like a good design to start with! Let's keep an open mind and iterate if we see improvements.

**Comment by Betree** [comment]
> Looks like a good design to start with! Let's keep an open mind and iterate if we see improvements.

@znarf Thanks for the feedback, will do :rocket: It's an easy one to update since we're hiding the page behind a feature flag for now.

**Review by SudharakaP — CHANGES_REQUESTED** [review]
@Betree : Seems the `returns acurate metrics for requested month` test is failing. I haven't pinpointed what exactly impacted the failure, but seems it's related to this PR.

**Comment by Betree** [comment]
> @Betree : Seems the `returns acurate metrics for requested month` test is failing. I haven't pinpointed what exactly impacted the failure, but seems it's related to this PR. thinking

We'll need to fix the tests. I've moved the blocking change to https://github.com/opencollective/opencollective-api/pull/6593 as it's not required for this PR.

**Pull request merged**
