### PR TITLE
Fix Transaction.amountInHostCurrency for feesPayer == PAYEE

### PR DESCRIPTION
**Pull request by kewitz**
- [x] Fix how we calculate amountInHostCollective on DEBITS
- [x] Write a migration to fix existing records

### CODE REVIEW

**Review by znarf — COMMENTED** [review]
We have a transaction validator, could be interesting to use it as it would have catch the issue originally.

```
await Transaction.validate(transaction);
```

**Comment by kewitz** [comment]
> We have a transaction validator, could be interesting to use it as it would have catch the issue originally. To be used in tests:
> 
> ```
> await Transaction.validate(transaction);
> ```

@znarf 
Interestingly enough, we commented the check for `amountInHostCurrency in oppositeTransaction should match`.
This fix is literally rewriting this rule to `amountInHostCurrency should match amount * fxRate`, are we sure about this?

**Comment by znarf** [comment]
The commented test is between the transaction value and the opposite transaction value. 

The normal check is enforced:

```
    Transaction.assertAmountsLooselyEqual(
      Math.round(transaction.amountInHostCurrency / hostCurrencyFxRate),
      transaction.amount,
      'amountInHostCurrency should match amount',
    );
```

**Comment by znarf** [comment]
What about validating Transactions in the test suite like I suggested?

**Comment by kewitz** [comment]
@znarf I don't like that idea, this function is not unit-tested and has some caveats.
Ideally, `Transaction.validate` method would have its own unit tests and these tests would break only when refactoring the method itself.
Also, having redundant check on tests is a good and not a bad thing.

**Review by znarf — APPROVED** [review]

**Pull request merged**
