### PR TITLE
Allow delete expense for SPAM

### PR DESCRIPTION
**Pull request by Betree**

### CODE REVIEW

**Comment by znarf** [comment]
Small question, where is it coming from?

In some cases, it's handy to have SPAM expenses not deleted so we can have a look at them through the interface.

**Comment by Betree** [comment]
@znarf It's coming from https://opencollective.slack.com/archives/G46PNRCGP/p1643620342761559. From the collective admin point of view, I think it's expected that SPAM gets removed from their pages.

**Comment by znarf** [comment]
Except the single expense page, in which screen is it appearing?

**Comment by Betree** [comment]
@znarf Only there I think, but the feedback was:
> a facebook open source admin marked an expense as spam, but then realized that his name appears in the trail as having marked the expense as spam and he'd rather not have the spammer see this

**Comment by znarf** [comment]
Ok, if we allow deletion of `rejected` then why not `spam`. But we have to remember that as soon as we delete, we loose the single expense page and the context (change of status, history, comments).

**Pull request merged**
