### PR TITLE
Update GraphQL to v14

### PR DESCRIPTION
**Pull request by eloyekunle**
Related: https://github.com/opencollective/opencollective-frontend/pull/1846
Ref: opencollective/opencollective#1658

### CODE REVIEW

**Comment by eloyekunle** [comment]
@znarf 

Here's why the Dates will always be coerced to their Unix time representation: https://github.com/graphql/graphql-js/blob/d4140766e0d2add0f82b22fe6e6354de4afc0f3c/src/type/scalars.js#L125.

I'll be using a custom GraphQL scalar type to represent the datetimes.

**Comment by znarf** [comment]
@eloyekunle Looks like a great solution! Do you understand why the `test-bdd` test are not passing?

**Comment by eloyekunle** [comment]
It's related to expenses. I'm looking into it now.

**Comment by eloyekunle** [comment]
@znarf It's fixed now.

**Comment by znarf** [comment]
@eloyekunle seems like a warning of a breaking change in the API.

What is change in the GraphQL package that is triggering that? Can that be fixed in the API instead of updating the test?

**Comment by znarf** [comment]
I pushed a matching branch on frontend to test if the update is breaking anything in e2e tests.

https://circleci.com/gh/opencollective/opencollective-frontend/tree/feat%2Fupdate-graphql

**Comment by eloyekunle** [comment]
The breaking change was made here: graphql/graphql-js#1382.

It means cases where the frontend sends `Int` values as `String` need to be changed.

**Comment by znarf** [comment]
@eloyekunle Can the breaking change fixed in the API instead of updating the test?

**Comment by eloyekunle** [comment]
@znarf 

Trying to fix it means creating a new scalar type for `Integers` that will also accept `Strings` and coerce them to `Integers`.

I've recognized two instances affected in the frontend and opened a PR for it: https://github.com/opencollective/opencollective-frontend/pull/1846.

**Comment by znarf** [comment]
@eloyekunle Thank you for your answer. Hope our coverage is great! 🤞

**Comment by eloyekunle** [comment]
The main things to look out for are cases where the Frontend is currently sending `Integers` as `Strings`. In such cases, the `String` should be parsed to `Integer` first, before sending to the API.

I'm sure there'll only be a few (if any) such cases left.

**Comment by znarf** [comment]
@eloyekunle What's the behavior if we don't? It's triggering a GraphQL error in the new version?

**Comment by eloyekunle** [comment]
Yes, it triggers an error.
Something like:

```
GraphQL v1 error: Variable "$id" got invalid value "10890"; Expected type Int; Int cannot represent non-integer value: "10890"
```

**Comment by eloyekunle** [comment]
Ping @znarf, What's left to merge this?

**Comment by znarf** [comment]
@eloyekunle It's good. I usually prefer to merge and deploy changes like that early in the week.

**Pull request merged**
