### PR TITLE
fix: typo in 'oneThousandBackers' tweet

### PR DESCRIPTION
**Pull request by david-allison-1**
Will likely want a test from someone more familiar with the project as a follow-on.

Came across this in the source, looked obviously incorrect.

### CODE REVIEW

**Comment by david-allison-1** [comment]
Test failure (doesn't seem relevant): https://github.com/opencollective/opencollective-api/pull/5104/checks?check_run_id=1692195785#step:9:43

<details>

```
error: uncaughtException: self._addDefaultMeta is not a function
TypeError: self._addDefaultMeta is not a function
    at DerivedLogger.<computed> (/home/runner/work/opencollective-api/opencollective-api/node_modules/winston/lib/winston/create-logger.js:80:14)
    at /home/runner/work/opencollective-api/opencollective-api/node_modules/package-hash/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:156:23) {"error":{},"stack":"TypeError: self._addDefaultMeta is not a function\n    at DerivedLogger.<computed> (/home/runner/work/opencollective-api/opencollective-api/node_modules/winston/lib/winston/create-logger.js:80:14)\n    at /home/runner/work/opencollective-api/opencollective-api/node_modules/package-hash/node_modules/graceful-fs/graceful-fs.js:61:14\n    at FSReqCallback.oncomplete (fs.js:156:23)","exception":true,"date":"Wed Jan 13 2021 01:40:31 GMT+0000 (Coordinated Universal Time)","process":{"pid":3982,"uid":1001,"gid":116,"cwd":"/home/runner/work/opencollective-api/opencollective-api","execPath":"/opt/hostedtoolcache/node/12.20.0/x64/bin/node","version":"v12.20.0","argv":["/opt/hostedtoolcache/node/12.20.0/x64/bin/node","/home/runner/work/opencollective-api/opencollective-api/node_modules/.bin/mocha","--ignore","test/server/graphql/**"],"memoryUsage":{"rss":804151296,"heapTotal":725680128,"heapUsed":702709168,"external":2495808,"arrayBuffers":802639}},"os":{"loadavg":[1.82,0.97,0.39],"uptime":182},"trace":[{"column":14,"file":"/home/runner/work/opencollective-api/opencollective-api/node_modules/winston/lib/winston/create-logger.js","function":"DerivedLogger.<computed>","line":80,"method":"<computed>","native":false},{"column":14,"file":"/home/runner/work/opencollective-api/opencollective-api/node_modules/package-hash/node_modules/graceful-fs/graceful-fs.js","function":null,"line":61,"method":null,"native":false},{"column":23,"file":"fs.js","function":"FSReqCallback.oncomplete","line":156,"method":"oncomplete","native":false}]}
{"error":{},"level":"error","message":"uncaughtException: self._addDefaultMeta is not a function\nTypeError: self._addDefaultMeta is not a function\n    at DerivedLogger.<computed> (/home/runner/work/opencollective-api/opencollective-api/node_modules/winston/lib/winston/create-logger.js:80:14)\n    at /home/runner/work/opencollective-api/opencollective-api/node_modules/package-hash/node_modules/graceful-fs/graceful-fs.js:61:14\n    at FSReqCallback.oncomplete (fs.js:156:23)","stack":"TypeError: self._addDefaultMeta is not a function\n    at DerivedLogger.<computed> (/home/runner/work/opencollective-api/opencollective-api/node_modules/winston/lib/winston/create-logger.js:80:14)\n    at /home/runner/work/opencollective-api/opencollective-api/node_modules/package-hash/node_modules/graceful-fs/graceful-fs.js:61:14\n    at FSReqCallback.oncomplete (fs.js:156:23)","exception":true,"date":"Wed Jan 13 2021 01:40:31 GMT+0000 (Coordinated Universal Time)","process":{"pid":3982,"uid":1001,"gid":116,"cwd":"/home/runner/work/opencollective-api/opencollective-api","execPath":"/opt/hostedtoolcache/node/12.20.0/x64/bin/node","version":"v12.20.0","argv":["/opt/hostedtoolcache/node/12.20.0/x64/bin/node","/home/runner/work/opencollective-api/opencollective-api/node_modules/.bin/mocha","--ignore","test/server/graphql/**"],"memoryUsage":{"rss":804151296,"heapTotal":725680128,"heapUsed":702709168,"external":2495808,"arrayBuffers":802639}},"os":{"loadavg":[1.82,0.97,0.39],"uptime":182},"trace":[{"column":14,"file":"/home/runner/work/opencollective-api/opencollective-api/node_modules/winston/lib/winston/create-logger.js","function":"DerivedLogger.<computed>","line":80,"method":"<computed>","native":false},{"column":14,"file":"/home/runner/work/opencollective-api/opencollective-api/node_modules/package-hash/node_modules/graceful-fs/graceful-fs.js","function":null,"line":61,"method":null,"native":false},{"column":23,"file":"fs.js","function":"FSReqCallback.oncomplete","line":156,"method":"oncomplete","native":false}]}
```

**Comment by david-allison-1** [comment]
Aside: I'd also question the hardcoded string `oneHundred`. It doesn't seem to match `milestones.js`

https://github.com/opencollective/opencollective-api/blob/5fab217ae76b5c67b9f4e759d57769e2a1bf3329/server/lib/twitter.js#L129

https://github.com/opencollective/opencollective-api/blob/a451b3089b095ea1271b732c8ab3bf5caba6c47b/cron/10mn/milestones.js#L115-L134

**Review by Betree — APPROVED** [review]
Nice catch!

**Comment by Betree** [comment]
I'm not sure what's wrong with the tests, you seem to be running on latest master. I'm looking into it

**Comment by Betree** [comment]
The rebase seemed to work: https://github.com/opencollective/opencollective-api/pull/5107

**Pull request merged**
