### PR TITLE
Expose activities for contributions (orders)

### PR DESCRIPTION
**Pull request by JoyLubega**
Part of: https://github.com/opencollective/opencollective/issues/6480

This Pr adds activities for Orders on the API

### CODE REVIEW

**Review by Betree — COMMENTED** [review]
This is great @JoyLubega! I've added a comment on https://github.com/opencollective/opencollective/issues/6480#issuecomment-1517352796 to document the activities we'd like to see here.

Could you update the PR description to replace "Resolve" by "Part of"? This shouldn't close https://github.com/opencollective/opencollective/issues/6480 as we'll still need a frontend update after it.

**Comment by Betree** [comment]
Hi @JoyLubega, do you need any assistance with this one? Happy to take it over from there if you don't have the bandwidth to iterate now.

**Comment by JoyLubega** [comment]
Yes that’s fine. My laptop has issues and it might take time for it to be
fixed

**Comment by Betree** [comment]
> Yes that’s fine. My laptop has issues and it might take time for it to be fixed

Good luck fixing them, and thanks for kickstarting the work on this one.

**Review by kewitz — APPROVED** [review]
Got to love consistency.

**Pull request merged**
