### PR TITLE
Expense buget stats to count distinct expense ids

### PR DESCRIPTION
**Pull request by kewitz**

### CODE REVIEW

**Comment by znarf** [comment]
Nice. Alternative, kind = 'EXPENSE' on the Transactions join ?

**Comment by kewitz** [comment]
@znarf I'm not sure, it depends if we want to display the net amount of the expense or include the payment processor fees. I'm going with the hypothesis that they want to see the total amount.

Also, I'm refactoring this two functions to use Sequelize instead a raw query, the PR is almost done.

**Comment by znarf** [comment]
Sounds good.

**Comment by kewitz** [comment]
Merging this to fix the bug. I will wait for a review on #9873.

**Pull request merged**
